team_identifiers = (
    {'nickname': u'Hawks', 'abbr': u'ATL', 'location': u'Atlanta'},
    {'nickname': u'Nets', 'abbr': u'BKN', 'location': u'Brooklyn'},
    {'nickname': u'Celtics', 'abbr': u'BOS', 'location': u'Boston'},
    {'nickname': u'Bobcats', 'abbr': u'CHA', 'location': u'Charlotte'},
    {'nickname': u'Bulls', 'abbr': u'CHI', 'location': u'Chicago'},
    {'nickname': u'Cavaliers', 'abbr': u'CLE', 'location': u'Cleveland'},
    {'nickname': u'Mavericks', 'abbr': u'DAL', 'location': u'Dallas'},
    {'nickname': u'Nuggets', 'abbr': u'DEN', 'location': u'Denver'},
    {'nickname': u'Pistons', 'abbr': u'DET', 'location': u'Detroit'},
    {'nickname': u'Warriors', 'abbr': u'GSW', 'location': u'Golden State'},
    {'nickname': u'Rockets', 'abbr': u'HOU', 'location': u'Houston'},
    {'nickname': u'Pacers', 'abbr': u'IND', 'location': u'Indiana'},
    {'nickname': u'Clippers', 'abbr': u'LAC', 'location': u'Los Angeles'},
    {'nickname': u'Lakers', 'abbr': u'LAL', 'location': u'Los Angeles'},
    {'nickname': u'Grizzlies', 'abbr': u'MEM', 'location': u'Memphis'},
    {'nickname': u'Heat', 'abbr': u'MIA', 'location': u'Miami'},
    {'nickname': u'Bucks', 'abbr': u'MIL', 'location': u'Milwaukee'},
    {'nickname': u'Timberwolves', 'abbr': u'MIN', 'location': u'Minnesota'},
    {'nickname': u'Hornets', 'abbr': u'NOH', 'location': u'New Orleans'},
    {'nickname': u'Knicks', 'abbr': u'NYK', 'location': u'New York'},
    {'nickname': u'Thunder', 'abbr': u'OKC', 'location': u'Oklahoma'},
    {'nickname': u'Magic', 'abbr': u'ORL', 'location': u'Orlando'},
    {'nickname': u'76ers', 'abbr': u'PHI', 'location': u'Philadelphia'},
    {'nickname': u'Suns', 'abbr': u'PHX', 'location': u'Phoenix'},
    {'nickname': u'Trail Blazers', 'abbr': u'POR', 'location': u'Portland'},
    {'nickname': u'Kings', 'abbr': u'SAC', 'location': u'Sacramento'},
    {'nickname': u'Spurs', 'abbr': u'SAS', 'location': u'San Antonio'},
    {'nickname': u'Raptors', 'abbr': u'TOR', 'location': u'Toronto'},
    {'nickname': u'Jazz', 'abbr': u'UTA', 'location': u'Utah'},
    {'nickname': u'Wizards', 'abbr': u'WAS', 'location': u'Washington'},
)

team_identifiers = (
    {
      'abbr': u'ATL',
      'location': u'Atlanta',
      'nickname': u'Hawks',
      'stats_inc_id': u'1',
      'conference': u'Eastern',
      'division': u'Southeast',
    },
    {
      'abbr': u'BKN',
      'location': u'Brooklyn',
      'nickname': u'Nets',
      'stats_inc_id': u'17',
      'conference': u'Eastern',
      'division': u'Atlantic',
    },
    {
      'abbr': u'BOS',
      'location': u'Boston',
      'nickname': u'Celtics',
      'stats_inc_id': u'2',
      'conference': u'Eastern',
      'division': u'Atlantic',
    },
    {
      'abbr': u'CHA',
      'location': u'Charlotte',
      'nickname': u'Bobcats',
      'stats_inc_id': u'74',
      'conference': u'Eastern',
      'division': u'Southeast',
    },
    {
      'abbr': u'CHI',
      'location': u'Chicago',
      'nickname': u'Bulls',
      'stats_inc_id': u'4',
      'conference': u'Eastern',
      'division': u'Central',
    },
    {
      'abbr': u'CLE',
      'location': u'Cleveland',
      'nickname': u'Cavaliers',
      'stats_inc_id': u'5',
      'conference': u'Eastern',
      'division': u'Central',
    },
    {
      'abbr': u'DAL',
      'location': u'Dallas',
      'nickname': u'Mavericks',
      'stats_inc_id': u'6',
      'conference': u'Western',
      'division': u'Southwest',
    },
    {
      'abbr': u'DEN',
      'location': u'Denver',
      'nickname': u'Nuggets',
      'stats_inc_id': u'7',
      'conference': u'Western',
      'division': u'Northwest',
    },
    {
      'abbr': u'DET',
      'location': u'Detroit',
      'nickname': u'Pistons',
      'stats_inc_id': u'8',
      'conference': u'Eastern',
      'division': u'Central',
    },
    {
      'abbr': u'GS',
      'location': u'Golden State',
      'nickname': u'Warriors',
      'stats_inc_id': u'9',
      'conference': u'Western',
      'division': u'Pacific',
    },
    {
      'abbr': u'HOU',
      'location': u'Houston',
      'nickname': u'Rockets',
      'stats_inc_id': u'10',
      'conference': u'Western',
      'division': u'Southwest',
    },
    {
      'abbr': u'IND',
      'location': u'Indiana',
      'nickname': u'Pacers',
      'stats_inc_id': u'11',
      'conference': u'Eastern',
      'division': u'Central',
    },
    {
      'abbr': u'LAC',
      'location': u'Los Angeles',
      'nickname': u'Clippers',
      'stats_inc_id': u'12',
      'conference': u'Western',
      'division': u'Pacific',
    },
    {
      'abbr': u'LAL',
      'location': u'Los Angeles',
      'nickname': u'Lakers',
      'stats_inc_id': u'13',
      'conference': u'Western',
      'division': u'Pacific',
    },
    {
      'abbr': u'MEM',
      'location': u'Memphis',
      'nickname': u'Grizzlies',
      'stats_inc_id': u'51',
      'conference': u'Western',
      'division': u'Southwest',
    },
    {
      'abbr': u'MIA',
      'location': u'Miami',
      'nickname': u'Heat',
      'stats_inc_id': u'14',
      'conference': u'Eastern',
      'division': u'Southeast',
    },
    {
      'abbr': u'MIL',
      'location': u'Milwaukee',
      'nickname': u'Bucks',
      'stats_inc_id': u'15',
      'conference': u'Eastern',
      'division': u'Central',
    },
    {
      'abbr': u'MIN',
      'location': u'Minnesota',
      'nickname': u'Timberwolves',
      'stats_inc_id': u'16',
      'conference': u'Western',
      'division': u'Northwest',
    },
    {
      'abbr': u'NO',
      'location': u'New Orleans',
      'nickname': u'Pelicans',
      'stats_inc_id': u'3',
      'conference': u'Western',
      'division': u'Southwest',
    },
    {
      'abbr': u'NY',
      'location': u'New York',
      'nickname': u'Knicks',
      'stats_inc_id': u'18',
      'conference': u'Eastern',
      'division': u'Atlantic',
    },
    {
      'abbr': u'OKC',
      'location': u'Oklahoma City',
      'nickname': u'Thunder',
      'stats_inc_id': u'25',
      'conference': u'Western',
      'division': u'Northwest',
    },
    {
      'abbr': u'ORL',
      'location': u'Orlando',
      'nickname': u'Magic',
      'stats_inc_id': u'19',
      'conference': u'Eastern',
      'division': u'Southeast',
    },
    {
      'abbr': u'PHI',
      'location': u'Philadelphia',
      'nickname': u'76ers',
      'stats_inc_id': u'20',
      'conference': u'Eastern',
      'division': u'Atlantic',
    },
    {
      'abbr': u'PHO',
      'location': u'Phoenix',
      'nickname': u'Suns',
      'stats_inc_id': u'21',
      'conference': u'Western',
      'division': u'Pacific',
    },
    {
      'abbr': u'POR',
      'location': u'Portland',
      'nickname': u'Trail Blazers',
      'stats_inc_id': u'22',
      'conference': u'Western',
      'division': u'Northwest',
    },
    {
      'abbr': u'SA',
      'location': u'San Antonio',
      'nickname': u'Spurs',
      'stats_inc_id': u'24',
      'conference': u'Western',
      'division': u'Southwest',
    },
    {
      'abbr': u'SAC',
      'location': u'Sacramento',
      'nickname': u'Kings',
      'stats_inc_id': u'23',
      'conference': u'Western',
      'division': u'Pacific',
    },
    {
      'abbr': u'TOR',
      'location': u'Toronto',
      'nickname': u'Raptors',
      'stats_inc_id': u'50',
      'conference': u'Eastern',
      'division': u'Atlantic',
    },
    {
      'abbr': u'UTA',
      'location': u'Utah',
      'nickname': u'Jazz',
      'stats_inc_id': u'26',
      'conference': u'Western',
      'division': u'Northwest',
    },
    {
      'abbr': u'WAS',
      'location': u'Washington',
      'nickname': u'Wizards',
      'stats_inc_id': u'27',
      'conference': u'Eastern',
      'division': u'Southeast',
    }
)

def _keyvals_match(x, y):
    for k, v in x.iteritems():
        if k not in y or y[k] != v:
            return False
    else:
        return True

def find_team(**kwargs):
    for team in team_identifiers:
        if _keyvals_match(kwargs, team):
            return team
